name: bvvm
description: A Flutter package that aids in developing using the BVVM pattern (BLoC, View, ViewModel).
version: 0.0.1+1
homepage: https://github.com/camrongiuliani/flutter_bvvm

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0

  event_bus: ^2.0.0

  get_it: ^7.2.0

  observable_value: ^0.0.1+2

  element_tree_child_locator: ^0.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
